version: '3'



services:
  ctf-train-sqli:
    build: .
    image: ctf-train-sqli
    container_name: ctf-train-sqli
    networks:
      - traefik_challsLAN
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:/ctf-train-sqli/;ReplacePathRegex: ^/ctf-train-sqli/(.*) /$$1"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_challsLAN"
    volumes:
      - ./www_site:/var/www/html/


networks:
  traefik_challsLAN:
    external: true
